IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'picture')
BEGIN
	CREATE TABLE [dbo].[picture](
		[id_picture] [int] IDENTITY(1,1) NOT NULL,
		[binary_data] [varbinary](max) NOT NULL,
		CONSTRAINT [PK_picture] PRIMARY KEY CLUSTERED
		(
			[id_picture] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
