IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'text_block' AND CONSTRAINT_TYPE='PRIMARY KEY')
	ALTER TABLE text_block ADD CONSTRAINT [PK_text_block] PRIMARY KEY CLUSTERED
	(
		[id_text_block] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
